name: Veracode Static Scan

on:
  pull_request_target:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r symon-package-tap-mssql.zip .
      - name: Get timestamp
        run: echo TIMESTAMP=$(date +%Y-%m-%d_%H:%M:%S) >> $GITHUB_ENV
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: ELT_tap-mssql
          createprofile: false
          filepath: ./symon-package-tap-mssql.zip
          version: ${{ env.TIMESTAMP }}
          vid: ${{ secrets.VERACODE_API_KEY_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY_SECRET }}
          scantimeout: 120
          criticality: High
